modLoader = "javafml"
loaderVersion = "[47,)"
license = "Custom"

[[mods]]
modId = "camping"
version = "${version}"
displayName = "[Let's Do] Camping"
authors = "satisfy, jason13"
description = '''
Let's sleep outside today! Grab your backpack, pack your tent, the grill, and the sleeping bag, and let's go!'''
logoFile = "pack.png"

[[dependencies.camping]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.camping]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.camping]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"